### ISSUE TITLE
conio crashes when line wrap occurs

### ISSUE THREAD

**Issue by jedimatt42** [tursilion/libti99#13]
I broke things good didn't I :)  

Your fixes to use a mode state is way better than the address based guesswork going on that I propagated.. But there is still at least a problem with scrolling from putc. 

I'll try to fix it this week/weekend...

**Comment by tursilion** [comment]
Wasn't just you - I found breakage from pretty much every pull request I've accepted. ;)

What's "a problem"? ;) Post a reproduction sample and let me fix it. ;)

**Comment by tursilion** [comment]
(Does that mean the test app crashes for you? Is it only crashing in 30 line mode?)

**Comment by tursilion** [comment]
I take it back, I will wait for your fix! ;)

**Comment by jedimatt42** [comment]
It was a simple case in my Force Command help system... where I just use cputc to copy one character at a time from ROM.. when it got to the right hand edge of the screen and wrapped, the system would crash out and go through powerup again.. I thought it was happening in my 'help' command. 

*I cannot reproduce it* in js99er, in ForceCommand or in TESTLIB, which already has coverage for that case. 
*I cannot reproduce it* in MAME or on F18A hardware either.

So, I'll close this issuue... TESTLIB already has coverage for what I thought was failing, and it passes.

**Comment by tursilion** [comment]
Huh.. thanks for taking a look at least!
