### ISSUE TITLE
[feature] Would you port this lib to pcc-tms9995

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [tursilion/libti99#21]
Have you looked at:
https://github.com/EtchedPixels/pcc-tms9995-support
by Alan Cox

His compiler may be a really good one considering what he has done in the past.
I have tried CC6303 also by him (recent C compiler for the Motorola 6800/6803/6303) and I have also tried Linux (LoL).

Would you consider porting your lib to pcc-tms9995 in the future?

**Comment by tursilion** [comment]
I write code based on my needs. Anything else I charge for. ;)

**Comment by tursilion** [comment]
(But, out of curiosity, what doesn't build?)

**Comment by Fabrizio-Caruso** [comment]
Did I say anything won't build? This "issue" is only a suggestion for you as you may find the new compiler interesting for your own needs. In the other issue. I can close this issue. Feel free to reopen it if you think it is necessary.

**Comment by tursilion** [comment]
Well... if it builds, then what porting is needed? You asked if I would port it to another compiler, but I wasn't sure what part didn't "just work".

**Comment by Fabrizio-Caruso** [comment]
HI, I haven't tried your library with Alan's compiler. And I haven't tried his compiler, either, but I plan to.

I am not sure I understand everything Alan says in the https://github.com/EtchedPixels/pcc-tms9995-support/blob/main/README.md
In particular he writes:
```

If you are usimg this toolchain with code intended for the gcc compiler note that the compiler ABI is entirely different. R13 is a downward growing stack (usually placed at 0x4000), R12 is used as a frame pointer, and the first two arguments are passed in R4 and R5 (or the first long argument). R0-R5 are scratch, R1 is the return value or R0/R1 for 32bit. R8-R15 should be preserved except for R11 which is used for BL as normal.

The assembler syntax is also slightly more conventional. The use of 'r' to indicate a register is mandatory, and hexadecimal is indicated by 0x or $. The '<' and '>' symbols select the upper and lower byte of a value as with the rest of the assemblers in the toolkit used.

```
Does it imply I cannot link your library with object files produced by his compiler? Should the object files and library use some common conventions? I am not an expert. So forgive me if I am saying something stupid.

   Fabrizio



________________________________
De : Mike Brent ***@***.***>
Envoyé : jeudi 7 avril 2022 22:52
À : tursilion/libti99 ***@***.***>
Cc : Fabrizio Caruso ***@***.***>; State change ***@***.***>
Objet : Re: [tursilion/libti99] [feature] Would you port this lib to pcc-tms9995 (Issue #21)


Well... if it builds, then what porting is needed? You asked if I would port it to another compiler, but I wasn't sure what part didn't "just work".

**Comment by tursilion** [comment]
No, you're fine. The ABI is how the underlying calls work, so it only matters when it comes to assembly language functions. I don't think there are any in libti99 except for the VGM player, which is deprecated anyway in favor of VGMComp2. You'd probably have to build with his compiler first to make sure the function calls work, but as long as you did that the code should all be fine.
