### ISSUE TITLE
[info/bug] Weird bug in cast+shift+add triggered by cprintf

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [tursilion/libti99#25]
Hi!
Could this weird bug/problem be somehow caused or triggered by `cprintf` ?

https://github.com/mburkley/tms9900-gcc/issues/65

Probably this bug was not present before Mark's changes. 
At least it was not shown in the only game of mine affected by this bug.

**Comment by tursilion** [comment]
Since Mark has marked it fixed I'm going to say no and close this. ;)
